- name: Populate Tower
  hosts: control_nodes
  gather_facts: yes
  become: yes

  tasks:
    - name: Create Tower student resources
      include_role:
        name: populate_tower
        tasks_from: windows.yml
      when:
        - towerinstall is defined
        - towerinstall|bool

- name: Configure Active Directory Domain Controller
  hosts: windows_domain_controllers
  gather_facts: yes
  # vars_files:
  #   - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - windows-ad-controller
  roles:
    - windows-ad-controller

- name: Configure Windows Servers
  hosts: windows
  gather_facts: True
  # vars_files:
  #   - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - windows_hosts
  roles:
    - windows-common

- name: Configure GitLab Host
  hosts: gitlab
  become: True
  gather_facts: True
  # vars_files:
  #   - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - gitlab
  roles:
    - { role: common }
    - { role: geerlingguy.gitlab }
#
# # Run post-config separate to avoid handler restart issue...
# - name: Gitlab Post Config
#   hosts: gitlab
#   become: True
#   gather_facts: True
#   vars_files:
#     - [ 'vars/custom.yml', 'vars/main.yml' ]
#   tags:
#     - gitlab
#   roles:
#     - { role: gitlab-postconfig }
